"""TOLAP Core - Models, merge algorithm, signing, and enforcement."""

from tolap_core.enums import (
    AssigneeType,
    FilterOperator,
    MaskType,
    PrincipalType,
    SigningAlgorithm,
    WriteOperation,
    mask_restrictiveness,
)
from tolap_core.models import (
    Assignee,
    AssignmentScope,
    AuditInfo,
    DelegationHop,
    EffectivePolicy,
    EndpointRules,
    FieldRules,
    IntegrityBlock,
    JudgeConfig,
    MaskingParameters,
    MaskingRule,
    ObjectRules,
    PolicyAssignment,
    PolicyDefinition,
    PolicyLimits,
    PolicyPermissions,
    PurposeProfile,
    RowFilter,
    SecurityContext,
    TagRules,
)
from tolap_core.serialization import (
    deserialize_effective_policy,
    deserialize_policy_assignment,
    deserialize_policy_definition,
    serialize,
)
from tolap_core.merger import merge
from tolap_core.resolution import resolve
from tolap_core.source_identity import (
    SourceCategory,
    SourceIdentity,
    parse_source_identity,
    source_category,
)
from tolap_core.kb_filter import (
    DEFAULT_KB_METADATA_KEYS,
    KbFilterClause,
    KbFilterOp,
    KbFilterResult,
    UnpushedRule,
    build_kb_filter,
)
from tolap_core.kb_providers import (
    KbFilterConfidence,
    KbProvider,
    RenderedKbFilter,
    render_kb_filter,
)
from tolap_core.context import (
    InMemoryReplayGuard,
    ReplayGuard,
    build_security_context,
    deserialize_context,
    serialize_context,
    sign_context,
    validate_context,
    validate_expiry,
)
from tolap_core.sql_rewriter import (
    DEFAULT_DIALECT,
    DEFAULT_ENFORCEMENT_MODE,
    SqlDialect,
    SqlEnforcementMode,
    SqlQueryPreparation,
    build_condition,
    build_where_clause,
    extract_referenced_fields,
    extract_table_name,
    prepare_sql_query,
    rewrite_query,
    unpushable_filters,
    validate_query,
)
from tolap_core.enforcement import (
    TARGET_ROW_UNKNOWN,
    AccessResult,
    FieldAccessResult,
    UnenforceableResultError,
    apply_field_masking,
    apply_masking,
    apply_object_size_ceiling,
    apply_result_limit,
    apply_similarity_floor,
    apply_result_pipeline,
    apply_row_filters,
    classify_result_shape,
    describe_result_shape,
    filter_by_tags,
    payload_write_fields,
    project_allowed_fields,
    strip_hidden_fields,
    validate_access,
    validate_endpoint,
    validate_field_access,
    validate_http_write,
    validate_action,
    validate_write,
    write_operation_for_method,
)
from tolap_core.delegation import MAX_DELEGATION_HOPS, validate_delegation_chain
from tolap_core.purpose_action import (
    UNDECLARED_CATEGORY_REASON,
    validate_http_action,
    validate_tool_action,
)
from tolap_core.judge import (
    DEFAULT_CONFIDENCE_THRESHOLD,
    DEFAULT_ESCALATION_THRESHOLD,
    DEFAULT_HISTORY_WINDOW,
    DEFAULT_MAX_LATENCY_MS,
    JUDGE_MODEL_MISMATCH_REASON,
    JUDGE_FAILED_REASON,
    NO_JUDGE_CONFIGURED_REASON,
    Judge,
    JudgeDisposition,
    JudgeOutcome,
    JudgeRequest,
    JudgeResult,
    build_judge_request,
    evaluate_judge,
    judge_disposition,
    judge_enabled,
    judge_history_window,
)
from tolap_core.history import ToolCallHistory

__all__ = [
    # Enums
    "AssigneeType",
    "FilterOperator",
    "MaskType",
    "PrincipalType",
    "SigningAlgorithm",
    "WriteOperation",
    "mask_restrictiveness",
    # Models
    "Assignee",
    "AssignmentScope",
    "AuditInfo",
    "DelegationHop",
    "EffectivePolicy",
    "EndpointRules",
    "FieldRules",
    "IntegrityBlock",
    "JudgeConfig",
    "MaskingParameters",
    "MaskingRule",
    "ObjectRules",
    "PolicyAssignment",
    "PolicyDefinition",
    "PolicyLimits",
    "PolicyPermissions",
    "PurposeProfile",
    "RowFilter",
    "SecurityContext",
    "TagRules",
    # Serialization
    "deserialize_effective_policy",
    "deserialize_policy_assignment",
    "deserialize_policy_definition",
    "serialize",
    # Merger
    "merge",
    # Resolution
    "resolve",
    # Source identity (connector-spec section 1)
    "SourceCategory",
    "SourceIdentity",
    "parse_source_identity",
    "source_category",
    # kb provider-side metadata filters (connector-spec section 7)
    "DEFAULT_KB_METADATA_KEYS",
    "KbFilterClause",
    "KbFilterConfidence",
    "KbFilterOp",
    "KbFilterResult",
    "KbProvider",
    "RenderedKbFilter",
    "UnpushedRule",
    "build_kb_filter",
    "render_kb_filter",
    # Context / Signing
    "InMemoryReplayGuard",
    "ReplayGuard",
    "build_security_context",
    "deserialize_context",
    "serialize_context",
    "sign_context",
    "validate_context",
    "validate_expiry",
    # Enforcement
    "AccessResult",
    "FieldAccessResult",
    "UnenforceableResultError",
    "apply_field_masking",
    "apply_masking",
    "apply_object_size_ceiling",
    "apply_result_limit",
    "apply_similarity_floor",
    "apply_result_pipeline",
    "apply_row_filters",
    "classify_result_shape",
    "describe_result_shape",
    "filter_by_tags",
    "project_allowed_fields",
    "strip_hidden_fields",
    "validate_access",
    "validate_endpoint",
    "validate_field_access",
    # Purpose binding (canonical spec section 15)
    "UNDECLARED_CATEGORY_REASON",
    "validate_action",
    "MAX_DELEGATION_HOPS",
    "validate_delegation_chain",
    "validate_http_action",
    "validate_tool_action",
    # The optional semantic judge (section 15.4). Advisory and strictly subtractive:
    # it can only take away an allowance the deterministic checks already granted.
    "DEFAULT_CONFIDENCE_THRESHOLD",
    "DEFAULT_ESCALATION_THRESHOLD",
    "DEFAULT_HISTORY_WINDOW",
    "DEFAULT_MAX_LATENCY_MS",
    "JUDGE_MODEL_MISMATCH_REASON",
    "JUDGE_FAILED_REASON",
    "NO_JUDGE_CONFIGURED_REASON",
    "Judge",
    "JudgeDisposition",
    "JudgeOutcome",
    "JudgeRequest",
    "JudgeResult",
    "ToolCallHistory",
    "build_judge_request",
    "evaluate_judge",
    "judge_disposition",
    "judge_enabled",
    "judge_history_window",
    # Write validation (connector spec section 4) -- pre-execution, fail-closed
    "TARGET_ROW_UNKNOWN",
    "payload_write_fields",
    "validate_http_write",
    "validate_write",
    "write_operation_for_method",
    # SQL query rewriting (a resource optimization; never replaces the pipeline)
    "DEFAULT_DIALECT",
    "DEFAULT_ENFORCEMENT_MODE",
    "SqlDialect",
    "SqlEnforcementMode",
    "SqlQueryPreparation",
    "build_condition",
    "build_where_clause",
    "extract_referenced_fields",
    "extract_table_name",
    "prepare_sql_query",
    "rewrite_query",
    "unpushable_filters",
    "validate_query",
]
