"""TOLAP Core - Models, merge algorithm, signing, and enforcement."""

from tolap_core.enums import (
    AssigneeType,
    FilterOperator,
    MaskType,
    SigningAlgorithm,
    WriteOperation,
    mask_restrictiveness,
)
from tolap_core.models import (
    Assignee,
    AssignmentScope,
    AuditInfo,
    EffectivePolicy,
    EndpointRules,
    FieldRules,
    IntegrityBlock,
    MaskingParameters,
    MaskingRule,
    ObjectRules,
    PolicyAssignment,
    PolicyDefinition,
    PolicyLimits,
    PolicyPermissions,
    RowFilter,
    SecurityContext,
    TagRules,
)
from tolap_core.serialization import (
    deserialize_effective_policy,
    deserialize_policy_assignment,
    deserialize_policy_definition,
    serialize,
)
from tolap_core.merger import merge
from tolap_core.resolution import resolve
from tolap_core.context import (
    build_security_context,
    deserialize_context,
    serialize_context,
    sign_context,
    validate_context,
    validate_expiry,
)
from tolap_core.sql_rewriter import (
    DEFAULT_DIALECT,
    SqlDialect,
    SqlQueryPreparation,
    build_condition,
    build_where_clause,
    extract_referenced_fields,
    extract_table_name,
    prepare_sql_query,
    rewrite_query,
    unpushable_filters,
    validate_query,
)
from tolap_core.enforcement import (
    TARGET_ROW_UNKNOWN,
    AccessResult,
    FieldAccessResult,
    UnenforceableResultError,
    apply_field_masking,
    apply_masking,
    apply_object_size_ceiling,
    apply_result_limit,
    apply_similarity_floor,
    apply_result_pipeline,
    apply_row_filters,
    classify_result_shape,
    describe_result_shape,
    filter_by_tags,
    payload_write_fields,
    project_allowed_fields,
    strip_hidden_fields,
    validate_access,
    validate_endpoint,
    validate_field_access,
    validate_http_write,
    validate_write,
    write_operation_for_method,
)

__all__ = [
    # Enums
    "AssigneeType",
    "FilterOperator",
    "MaskType",
    "SigningAlgorithm",
    "WriteOperation",
    "mask_restrictiveness",
    # Models
    "Assignee",
    "AssignmentScope",
    "AuditInfo",
    "EffectivePolicy",
    "EndpointRules",
    "FieldRules",
    "IntegrityBlock",
    "MaskingParameters",
    "MaskingRule",
    "ObjectRules",
    "PolicyAssignment",
    "PolicyDefinition",
    "PolicyLimits",
    "PolicyPermissions",
    "RowFilter",
    "SecurityContext",
    "TagRules",
    # Serialization
    "deserialize_effective_policy",
    "deserialize_policy_assignment",
    "deserialize_policy_definition",
    "serialize",
    # Merger
    "merge",
    # Resolution
    "resolve",
    # Context / Signing
    "build_security_context",
    "deserialize_context",
    "serialize_context",
    "sign_context",
    "validate_context",
    "validate_expiry",
    # Enforcement
    "AccessResult",
    "FieldAccessResult",
    "UnenforceableResultError",
    "apply_field_masking",
    "apply_masking",
    "apply_object_size_ceiling",
    "apply_result_limit",
    "apply_similarity_floor",
    "apply_result_pipeline",
    "apply_row_filters",
    "classify_result_shape",
    "describe_result_shape",
    "filter_by_tags",
    "project_allowed_fields",
    "strip_hidden_fields",
    "validate_access",
    "validate_endpoint",
    "validate_field_access",
    # Write validation (connector spec section 4) -- pre-execution, fail-closed
    "TARGET_ROW_UNKNOWN",
    "payload_write_fields",
    "validate_http_write",
    "validate_write",
    "write_operation_for_method",
    # SQL query rewriting (a resource optimization; never replaces the pipeline)
    "DEFAULT_DIALECT",
    "SqlDialect",
    "SqlQueryPreparation",
    "build_condition",
    "build_where_clause",
    "extract_referenced_fields",
    "extract_table_name",
    "prepare_sql_query",
    "rewrite_query",
    "unpushable_filters",
    "validate_query",
]
